FROM node:20-bookworm-slim

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm ci --only=production

COPY --chown=node:node . .

EXPOSE 3000

CMD [ "node", "dist/main.js" ]