FROM node:22-bookworm-slim

WORKDIR /app

ENV PORT=3000

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm ci --only=production

COPY --chown=node:node . .

EXPOSE 3000

CMD [ "node", "dist/main.js" ]
